blocknative/dreamboat

internal/mock/pkg/datastore.go
pkg/datastore.go
pkg/datastore_test.go
pkg/relay.go
pkg/relay_test.go
pkg/service.go
scripts/getpayload/main.go
scripts/submitblock/main.go

This PR fixes the payload delivery Data API. Previously the delivered payload was overwritten whenever a new block with the same slot was submitted. But now they are not. Delivered payloads and submitted blocks are stored separately.

fixed delivered payload Data API

---

internal/mock/pkg/datastore.go
pkg/datastore.go
pkg/datastore_test.go
pkg/relay.go
pkg/relay_test.go
pkg/service.go
pkg/service_test.go

This PR fixes the builder_blocks_received Data API call, so that now all blocks for every slot are returned. Previously just the latest block per slot was returned
The corresponding tests have been fixed, and all pass

Store multiple headers, instead of latest (for Data API)

---

pkg/api.go
pkg/service.go

This PR fixes the Data API `limit` and `cursor` parameters. Currently, `cursor` is used as lower limit instead of an upper limit and the `limit` does not enforce any limit, it's just used as a default value.

Fix cursor & limit

---

pkg/api.go
pkg/api_test.go
pkg/datastore.go
pkg/datastore_test.go

This PR 
(1) deduplicates Headers. Currently, headers are stored as an array, and when we add a new one we simply append to the list. However, this may lead to having hundreds of duplicate headers, which obscures the Data API. So, in this PR we add the logic for deduplicating the headers.
(2) Fixes the data API. Currently we are not correctly serving the indexed queries. We return more than what user asks for.
Before appending a new header we check if the tail of the headers is the same as the one currently being stored. For checking equality only the `BlockHash` is used.
I added a regression test for checking deduplication works as expected

Fix/improve Data API builder_blocks_received

---

pkg/relay.go

Explain what this PR accomplishes
- changes the source of the proposer_fee_recipient field to bidTrace as opposed to the eth execution payload feeRecipient value.
Explain the need or decisions which make this change necessary
- Currently when a builder with proposer payments sends blocks to our relay, it will now show the validators preferred fee recipient, but instead the fee recipient in the execution payload. This issue did not make itself known because the main builder being used with dreamboat in prod did not support proposer payments.
Briefly explain what components you modified or added, and how, to give context to your reviewers
- simple change of field source

propFeeRecipient from bidTrace not exec payload

---

internal/mock/pkg/beacon.go
internal/mock/pkg/datastore.go
internal/mock/pkg/relay.go
internal/mock/pkg/service.go
pkg/beacon.go
pkg/datastore_test.go
pkg/relay.go
pkg/relay_test.go
pkg/service.go
pkg/service_test.go

It is necessary to check whether the timestamp of the block submissions is the one expected for the corresponding slot. 
If validation is not implemented, then (correctly implemented) validators to reject the blocks the relay serves them.
Obtain Genesis time on relay initialization and compute expected timestamp on block submissions by doing `genesisTime + slot x 12`
Thank you to @metachris for notifying about this, and help make the relay more robust.

Add timestamp validation on block submission

---

cmd/dreamboat/main.go

Adds nanosecond precision to logs (JSON format only).
cc @bkellerman: for context, and in case you ever need to fix this somewhere else

Set JSON timestamp to RFC3339Nano.

---

pkg/relay/register.go

This PR fixes how the validator registrations are logged
Otherwise there are inconsistencies on how previously registrations were logged

only log successful registrations

---

pkg/api/api.go

Explain what this PR accomplishes
"Manually fuzz testing" and noticed submitBlock returns errors like:
```
{"code":400,"message":"EOF"}
```
when it should be 
```
{"code":400,"message":"EOF"}
```
like the other endpoints
Explain the need or decisions which make this change necessary
API consistency

fix submitBlock default error

---

pkg/service.go

This PR fixes `uint64` overflows on low slot numbers, when querying data api tail values. Currently, if the `headslot` is lower than `TTL/DurationPerSlot`, it overflows when retrieving tails of delivered payloads and submitted blocks.
I added checks in the stop values as well as the steps of the iteration over the slots when querying the tail.

Fix data api underflow on low slots

---

pkg/validators/validators.go

Fixes the observing of the metric `registerValidator-all`
Otherwise we don't get real numbers on the time it takes to process registrations
Add a `defer`, in order to observe after the function is finished

Fix registerValidator/all metric

---

pkg/service.go

Add the processing time to the slot processing log
We do not have observability on the time it takes to process a slot

add processingTime to the slot processing logs

---

pkg/service.go

Fix time precision to be milliseconds in the beacon state loop.
Otherwise, you cannot visualize this metric with other processing times, since they have different precisions

Change beacon log time precision to ms

---

pkg/validators/metrics.go

Removes duplicated metric 
Otherwise, the duplicated metrics override each other

remove duplicate metrics

---

pkg/beacon.go
pkg/relay/relay.go

This PR moves the PublishBlock call to before PutDelivered, in order to speed up as much as possible.
If the Storage is congested, then the PublishBlock will take too much time.

PublishBlock before storing "payload delivery" in data API

---

cmd/dreamboat/main.go

Correcting parameter name to say request instead of bundle

Correction in param name

---

pkg/relay/relay.go

Adds a log statement to record whenever an invalid parenthash is requested on GetHeader
This way we can debug if we fail to deliver bids due to invalid parenthash

Add log to record invalid parenthash

---

datastore/evidence/postgres/blocks.go

Fixes ms data precision returned by postgres dataapi.

Fix for μs to ms

---

beacon/client/client.go
beacon/client/mocks/mocks.go
beacon/client/multi.go
cmd/dreamboat/main.go
relay/mocks/mocks.go
relay/relay.go

Synchronous block propagation after:  https://github.com/flashbots/mev-boost-relay/pull/330

Synchronous block propagation

---

beacon/client/client.go
beacon/manager.go
cmd/dreamboat/main.go
structs/const.go

This PR checks whether the beacon nodes subscription to head events does not produce any event for more than two slots, and if so, it restarts the subscription.
Beacon node subscriptions are unstable, and we have detected that they do not produce any event for a long time, consequently desynchronizing the relay.

Force beacon reconnect

---

beacon/client/client.go

This PR improves new head events subscriptions so that it does not close the subscription unless there is not an event. Previously it closed also if event consumption was taking too much time. However, this has nothing to do with connection reset.

move timer reset

---

beacon/client/client.go

Add timeouts to all beacon queries 
This way we make sure we do not congest either the relay or the beacon with a lot of open connections, in case something goes wrong with the beacon client. The motivation is that we have seen beacon being unresponsive and taking an extremely long time to respond to queries.

add 20 seconds timeout to all beacon queries

---

beacon/client/client.go

This PR implements the logic to manually fetch the latest header in case the subscription fails to receive the event
This way, we do not always need to rely on the subscription. If it fails, we have a mechanism to fetch it manually, and keep the relay synced

Add logic to manually fetch header if subscription fails

---

beacon/client/client.go

This PR improves the logs on beacon header subscription
Makes it more precise, so that we now whether it's being restarted or manually being fetched.

Make subscription log more precise

---

relay/relay.go

Fix the overwriting of logs on GetPayload request
Otherwise we do not log important information about GetPayload request

Do not overwrite logger for GetPayload

---

beacon/manager.go

Add logic to wait for beacon syncing on relay initialization 
Otherwise, it fails when beacon is still syncing, instead of waiting

add logic to wait for syncing on initialization

---

beacon/client/client.go
beacon/manager.go
cmd/dreamboat/main.go

This PR improves logic for beacon subscription restart so that it checks whether there are 3 consecutive timeouts. If they are not consecutive and close in time, then it does not restart, it only fetches the latest header manually.
This avoids overly restarting subscriptions in networks like Goerli, where there are many missed slots per epoch.

Improve beacon subscription restart and logs

---

api/inner/inner.go
beacon/manager.go

The `missed slot` log is not correct, since the `headSlot` is set to new `slot` before analyzing the missed slots

Print correctly missed slots

---

datastore/warehouse/warehouse.go

Fix warehouse to initialize warehouse `cleanShutdown` flag
Otherwise it panics when closing/stopping the relay

initalize warehouse cleanShutdown

---

cmd/dreamboat/main.go
relay/submit.go
validators/storemanager.go

Add a new param for setting the TTL param for storing registrations
This is needed so that it is independent from the storage TTL

add ttl param for storeManager TTL

---

relay/relay.go
relay/submit.go

Delete 'stored in warehouse' logs
It does not provide any insight. Instead, we only log when something fails in warehouse

Delete 'stored in warehouse' logs

---

beacon/client/client.go

Delete print statement from beacon client payload attrs

delete print from beacon client payload attr

---

api/api.go
relay/metrics.go
relay/relay.go

This PR allows multiple `getPayload` requests for the same slot in order to address the issue of reduced chances of successful submission by distributed validators (DVT) when the first submitter's beacon node has connectivity issues. Currently, only one call of `getPayload` is allowed for the same slot, which limits the network outreach of the proposal to only one beacon node. By enabling multiple `getPayload` requests, each participant's Beacon node can independently POST `/eth/v1/builder/blinded_blocks` for the same slot, increasing the chances of successful submission by distributed validators.
The limitation of only allowing one `getPayload` call for the same slot negatively impacts the network outreach and reliability of the proposal submission process for distributed validators. By …

Allow getPayload retries for the same blockHash

---

datastore/warehouse/warehouse.go

This PR adds encoder information to the warehouse functionality, specifically to the header of the stored data. The encoder details are included to provide additional context and transparency about the encoding technique used for the stored information.
The inclusion of encoder information in the warehouse header is important for several reasons. It helps improve data management and retrieval processes by providing insights into the encoding technique applied to the stored data. This information is valuable for data analysis, debugging, and troubleshooting purposes. By including the encoder details, it becomes easier to identify and understand the encoding format, such as base64+gzip+json, used for the stored data.
In this PR, the modification is made to the `Warehouse` component. The …

Add encoder information to the warehouse header

---

datastore/datastore.go
stream/stream.go
structs/forks/capella/capella.go
structs/forks/capella/capella_test.go
structs/withdrawals.go

This Pull Request aimes at optimizing the stream functionality by implementing SSZ encode/decode for the `GetPayload` and `BidTrace` structs..
The changes made in this PR are necessary to enhance the performance, reliability, and compatibility of the stream component. By implementing SSZ encode/decode for the `GetPayload` and `BidTrace` structs, the serialization and deserialization processes are optimized, resulting in improved efficiency and streamlined data handling. These enhancements contribute to a more robust and efficient stream implementation.
In this PR, the following components were modified or added:
1. `datastore/datastore.go`: This file was updated to use the `BlockAndTraceExtended` struct for the Capella fork, improving the payload structure.
2. `stream/stream.go`: Changes …

Optimize Stream Functionality and Implement SSZ Encode/Decode for Improved Performance

---

relay/submit.go

- Add  `registeredGasLimit` field to the logger in `SubmitBlock`
Help us understand why some blocks fail validation because of an incorrect gas limit

Debug block gas usage
