pkg/service.go
This PR fixes the `cursor` parameter behavior on the Data API
This is necessary for correct live auditing of the relay
=> fix cursor parameter

go.mod
Explain what this PR accomplishes
upgrades go-boost-utils to v1.2.0
Explain the need or decisions which make this change necessary
latest flashbots/go-boost-utils fixes issue with decoding deposits https://github.com/flashbots/go-boost-utils/pull/40
Briefly explain what components you modified or added, and how, to give context to your reviewers
dependency only
=> go-boost-utils to v1.2.0

pkg/relay.go
This PR adds gaslimit and gasused for the header
=> Fix gaslimit and gasused

pkg/datastore_test.go
Fixes broken tests, that was assigning 2 different values and then testing it's equality
Broken tests
=> Add correct slot ids

pkg/datastore/headers.go, pkg/datastore/headers_test.go
Fix getting blocks by blockhash
=> Fix getting by blockhash

cmd/dreamboat/main.go, pkg/config.go, pkg/datastore/datastore_test.go, pkg/datastore/headers.go, pkg/datastore/headers_test.go, pkg/datastore/headerscontroller.go, pkg/service.go
Enabling some values to be changed as flags
=> Add params to env flags

pkg/relay/relay.go
What 🕵️‍♀️
Change getPayload so:
* Verification Signature call would not be enqueued with other verifications, just run synchronously
* DataAPI PutDelivered write, would be ran asynchronously being outside of the critical path.
Why 🔑
Performance improvements
=> GetPayload Performance improvements

cmd/dreamboat/main.go, pkg/relay/metrics.go, pkg/relay/processmanager.go, pkg/relay/register.go, pkg/relay/relay.go
Registration cache for validator registrations
To limit the number of registration updates
=> Registration cache

pkg/relay/processmanager.go
Change cache to work based on the assigned time
=> Change to the assigned time

pkg/service.go
This PR changes relay's initialisation behaviour. If the beacon node is syncing, instead of failing, it loops until the beacon node is synced. It sleeps 3 seconds before querying again the beacon. I think there is no need for using a more sophisticated backoff mechanism.
=> Wait until beacon node is synced on initialization

pkg/api/api.go, pkg/datastore/headers.go, pkg/relay/relay.go, pkg/service.go
Remove old storage format, add getHeader metrics
=> Post deploy cleanup 

cmd/dreamboat/main.go, pkg/datastore/validator/badger/badger.go, pkg/datastore/validator/postgres/postgres.go
Lazy Pre-populate validator's cache so it would not spam database after restart
=> Pre-populate validator cache

cmd/dreamboat/main.go, go.mod, go.sum, pkg/api/api.go, pkg/api/api_test.go, pkg/api/limitter.go, pkg/api/middleware.go
This work adds a rate limit in preparation for adding support for external builders.
=> Builder submission ratelimit

cmd/dreamboat/main.go, pkg/datastore/headers.go, pkg/datastore/headers_test.go
Optimizing header preload, by only fetching last 5 heights
=> add headers preload optimization

pkg/client/sim/fallback/fallback.go, pkg/client/sim/transport/gethhttp/gethhttp.go, pkg/client/sim/transport/gethrpc/gethrpc.go, pkg/client/sim/transport/gethws/client.go, pkg/relay/mocks/mocks.go, pkg/relay/relay.go, pkg/relay/submit.go
Do not perform any block simulation if simulation endpoints are not set
=> Disable simulation if configuration is not set

relay/submit.go, structs/metrics.go
This PR validates blocks asynchronously
This is for improving performance on block submissions
=> Add logic to run simulation validation asynchronously

api/api.go, beacon/manager.go, beacon/mocks/mocks.go, beacon/state.go, cmd/dreamboat/main.go, relay/mocks/mocks.go, relay/relay.go, relay/submit.go, structs/structs.go, validators/mocks/mocks.go, validators/validators.go
This PR allows submitting blocks from old slots
=> Submit old slot

api/api.go, beacon/mocks/mocks.go, relay/mocks/mocks.go, relay/relay.go, relay/submit.go, structs/blocks.go, structs/forks/bellatrix/bellatrix.go, structs/forks/capella/capella.go, validators/mocks/mocks.go
This PR adds additional checks to block submissions, and to GetHeader and GetPayload requests.
It is necessary to reinforce the checks to ensure the bids and payloads being served are valid.
=> Add additional checks

relay/submit.go
Fixes the error message when the randao is not found for block submission
=> fix randao error return message

client/sim/transport/gethws/client.go, client/sim/transport/gethws/gethws.go, cmd/dreamboat/main.go
Fixing ws connection leak on context closed
=> Ws connection fixes

beacon/client/client.go, cmd/dreamboat/main.go
Proposed improvements to force-beacon-reconnect branch
=> Proposed improvements

api/api.go, cmd/dreamboat/main.go, relay/relay.go
Add a check for rejecting GetPayload requests that occur too late
=> GetPayload check for rejecting late requests

api/api.go, beacon/client/client.go, cmd/dreamboat/main.go, relay/relay.go, structs/blocks.go, structs/forks/bellatrix/bellatrix.go, structs/forks/capella/capella.go, structs/structs.go
Add header validation to the GetPayload request so that the header sent in the request and the one the relay has been the same.
This is necessary for new security issue on malicious proposers
=> Payload validation on GetPayload

api/api.go, api/api_test.go, api/inner/inner.go, cmd/dreamboat/main.go
Allows to disable/enable particular endpoints without restarting the relay
=> Internal Endpoints API

api/api.go, api/inner/inner.go, cmd/dreamboat/main.go, datastore/datastore.go
Allows extracting submissions from badgerDB
=> Internal submission reader

beacon/client/client.go, beacon/client/mocks/mocks.go, beacon/client/multi.go, beacon/manager.go, beacon/mocks/mocks.go, beacon/state.go, cmd/dreamboat/main.go
This PR implements subscriptions to beacon for getting payload attributes, instead of waiting for head events and manually fetching them
Improves performance, because we do not pull the info, instead it is pushed to us
=> Payload sub

api/api.go, api/api_test.go, api/mocks/mocks.go, relay/relay.go, relay/submit.go, structs/api.go
Add a linkable token to trace multiple logs by source
=> Add traceable logs

beacon/manager.go, relay/submit.go
This PR extends the logs for providing more insights when there is a randao or withdrawals invalid error. Also, it logs whenever the randao or withdrawals state is overwritten
=> Observability on randao and withdrawals errors

beacon/manager.go, beacon/state.go
Do not allow overwriting payload attributes
Randao may change over a single slot incorrectly
=> Randao first

auction/auctioneer.go, beacon/manager.go, beacon/state.go, cmd/dreamboat/main.go, datastore/datastore.go, relay/metrics.go, relay/relay.go, relay/submit.go, stream/stream.go, stream/structs.go, structs/blocks.go, structs/cache.go, structs/const.go, structs/forks/bellatrix/bellatrix.go, structs/forks/capella/capella.go
Makes stream lighter, reducing the amount of data is streamed
To reduce pressure on the network and pubsub system
=> Make stream structs lightweight

auction/auctioneer.go, beacon/mocks/mocks.go, client/sim/transport/gethws/gethws.go, relay/mocks/mocks.go, relay/relay.go
Structures MEV per parent hash
=> Per parent MEV

api/api.go, api/api_test.go, api/inner/inner.go, api/limitter.go, cmd/dreamboat/config/manager.go, cmd/dreamboat/config/source/file/file.go, cmd/dreamboat/main.go, relay/config.go, relay/relay.go, relay/submit_test.go
- Fix for time.Duration
- Additional logging on parameters change
- Internal endpoint for current config observability.
=> Dynamic Config changes

README.md
Added disclaimer regarding suspension of Relay activity by Blocknative Team
=> doc: update readme with disclaimer
